update

diff --git a/bush/use_cc b/bush/use_cc
--- a/bush/use_cc
+++ b/bush/use_cc
@@ -20,6 +20,12 @@ if [ ${build_gnu} = "yes" ] ; then
     elif [ "`echo ${osx_vers} | sed -e 's:10.12::g'`" != "${osx_vers}" ] ; then
       cc_compiler=/opt/local/bin/gcc-mp-5
       cc_linker=/opt/local/bin/gcc-mp-5
+    elif [ "`echo ${osx_vers} | sed -e 's:10.13::g'`" != "${osx_vers}" ] ; then
+      cc_compiler=/opt/local/bin/gcc-mp-5
+      cc_linker=/opt/local/bin/gcc-mp-5
+    elif [ "`echo ${osx_vers} | sed -e 's:10.14::g'`" != "${osx_vers}" ] ; then
+      cc_compiler=/opt/local/bin/gcc-mp-8
+      cc_linker=/opt/local/bin/gcc-mp-8
     else
       echo 'bush/use_cc : gcc not found under /opt/local/bin.'
       exit
@@ -36,7 +42,7 @@ elif [ ${build_intel} = "yes" ] ; then
 
 elif [ ${build_clang} = "yes" ] ; then
   config_name=clang
-  
+
   found=no
   items="clang clang-3.9 clang-3.5 clang-3.4 clang-3.3"
   for item in ${items} ; do
@@ -51,9 +57,22 @@ elif [ ${build_clang} = "yes" ] ; then
   done
 
   if [ ${found} = no ] ; then
-    echo "${items} not found."
+    echo "bush/use_cc : ${items} not found."
     exit
   fi
+
+  if [ ${build_ansi} = "yes" ] ; then ccflags="${ccflags} -ansi"; fi
+  if [ ${build_pedantic} = "yes" ] ; then ccflags="${ccflags} -pedantic"; fi
+
+elif [ ${build_emcc} = "yes" ] ; then
+  config_name=emcc
+
+  ${bush_home}/check_app emcc 'bush/use_cc : emcc not found.'
+  use_status=$?;
+  if [ ${use_status} != 0 ] ; then exit; fi
+
+  cc_compiler=emcc
+  cc_linker=emcc
 
 elif [ ${build_sdk_mac} = "yes" -o ${build_sdk_mac_gnu} = "yes" ] ; then
 
@@ -104,19 +123,19 @@ elif [ ${build_cling_clang} = "yes" ] ; then
   config_name=cling_clang
 
   . ${bush_home}/use_cling
-  
+
   if [ "${cling_home}" = "" ] ; then
     echo "bush/use_cc : cling_home not defined."
     exit
   fi
-  
+
   if [ ${build_verbose} = yes ] ; then
     echo "bush/use_cc : cling_home is ${cling_home}."
   fi
 
   cc_compiler=${cling_home}/bin/clang
   cc_linker=${cpp_compiler}
-  
+
 elif [ ${build_sdk_ios} = "yes" -o ${build_sdk_ios_gnu} = "yes" ] ; then
 
   # options taken from the output of :
@@ -131,27 +150,6 @@ elif [ ${build_sdk_ios} = "yes" -o ${build_sdk_ios_gnu} = "yes" ] ; then
     cc_compiler=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/llvm-gcc-4.2
     cc_linker=${cc_compiler}
   fi
-
-  # see also use_cpp :
-  #sdk_dirs="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs /Developer/SDKs"
-  #sdk_verss="10.0 9.3 9.0 8.1 7.1 5.0"
-  #found=no
-  #for sdk_dir in ${sdk_dirs} ; do
-  #  for sdk_vers in ${sdk_verss} ; do
-  #    if [ ${found} = no ] ; then
-  #      ios_sdk="${sdk_dir}/iPhoneOS${sdk_vers}.sdk"
-  #      ios_vers=${sdk_vers}
-  #     if [ -d "${ios_sdk}" ] ; then found=yes;fi
-  #   fi
-  # done
-  #done
-  #if [ ${found} = no ] ; then
-  #  echo "bush/use_cc : iOS sdk not found."
-  #  exit
-  #fi
-  #echo "${ios_sdk}"
-  #echo "${ios_vers}"
-  #exit
 
   ios_sdk="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
   if [ ! -d "${ios_sdk}" ] ; then
@@ -177,7 +175,7 @@ elif [ ${build_sdk_ios} = "yes" -o ${build_sdk_ios_gnu} = "yes" ] ; then
   # the below is to stay consistent with use_cpp :
   ccflags="${ccflags} -fvisibility=hidden"
 
- #ccflags="${ccflags} -gdwarf-2 -mno-thumb" 
+ #ccflags="${ccflags} -gdwarf-2 -mno-thumb"
  #ccflags="${ccflags} -Os"
 
   mflags="${mflags} -fobjc-abi-version=2 -fobjc-legacy-dispatch"
@@ -216,6 +214,11 @@ elif [ ${build_visual} = "yes" ] ; then
     echo "bush/use_cc : build_visual : bush_home not defined."
     exit
   fi
+
+  ${bush_home}/check_app cl.exe 'bush/use_cc : cl.exe not found. You have to setup VisualC++.'
+  use_status=$?;
+  if [ ${use_status} != 0 ] ; then exit; fi
+
   cc_compiler=${bush_home}/vc++
 
   if [ "${build_set_x}" = "yes" ] ; then ccflags="${ccflags} -verbose"; fi
@@ -227,58 +230,13 @@ elif [ ${build_visual} = "yes" ] ; then
 elif [ ${build_sdk_android} = "yes" ] ; then
   config_name=sdk_android
 
-  sdk_home=/usr/local/Android/android-sdk_r16-macosx
+  . ${bush_home}/use_android
 
-  # WARNING : must be in sync with use_cpp, plugin, use/Android.
+  cc_compiler=${ndk_cc_compiler}
 
- #build_ndk_vers=r15b
-  build_ndk_vers=r7
-  build_ndk_vers=r10e
-  
-  ndk_home=/usr/local/Android/android-ndk-${build_ndk_vers}
-
-  if [ ${build_ndk_vers} = r7 ] ; then
-    ndk_bin=${ndk_home}/toolchains/arm-linux-androideabi-4.4.3/prebuilt/darwin-x86/bin
-    ndk_platform="${ndk_home}/platforms/android-9/arch-arm"
-  elif [ ${build_ndk_vers} = r10e ] ; then
-    ndk_bin=${ndk_home}/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin
-    ndk_platform="${ndk_home}/platforms/android-9/arch-arm"
-  else
-    echo "bush/use_cc : ndk version ${build_ndk_vers} not yet supported."
-    exit
-  fi    
-
-  cc_compiler=${ndk_bin}/arm-linux-androideabi-gcc
-
- #ccflags="${ccflags} -MMD -MP -MF <some .d path>"
- #ccflags="${ccflags} -O2 -DNDEBUG -g"
- #ccflags="${ccflags} -Ijni"
- #ccflags="${ccflags} -I${ndk_home}/sources/cxx-stl/system/include"
-
-  if [ ${build_ndk_vers} = r7 ] ; then
-    ccflags="${ccflags} -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__"
-    ccflags="${ccflags} -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__"
-  fi
-  
-  ccflags="${ccflags} -fpic"
-  ccflags="${ccflags} -ffunction-sections -funwind-tables -fstack-protector"
-  ccflags="${ccflags} -fomit-frame-pointer -fno-strict-aliasing"
-  ccflags="${ccflags} -finline-limit=64"
-  
-  ccflags="${ccflags} -mthumb"
-  ccflags="${ccflags} -Os"
-  ccflags="${ccflags} -march=armv5te -mtune=xscale -msoft-float"
-
-  ccflags="${ccflags} -Wno-psabi -Wa,--noexecstack"
-  
-  ccflags="${ccflags} -I${ndk_platform}/usr/include"
-  
+  ccflags="${ccflags} ${ndk_ccflags}"
   ccflags="${ccflags} -DANDROID"
 
-  if [ ${build_ndk_vers} = r10e ] ; then
-    ccflags="${ccflags} -no-canonical-prefixes -Wformat -Werror=format-security"
-  fi
-  
   cc_linker=${cc_compiler}
 
 else
@@ -291,8 +249,19 @@ if [ ${build_visual} = "yes" ] ; then
   if [ ${build_debug} = "yes" ] ; then
     ccflags="${ccflags} -g"
     cc_linker_flags="${cc_linker_flags} -g"
-  else    
+  else
     ccflags="${ccflags} -DNDEBUG"
+  fi
+
+elif [ ${build_emcc} = "yes" ] ; then
+
+  if [ ${build_debug} = "yes" ] ; then
+    ccflags="${ccflags} -g -g4"
+    ccflags="${ccflags} -s DEMANGLE_SUPPORT=1"
+    ccflags="${ccflags} -s ASSERTIONS=1"
+    ccflags="${ccflags} -Werror"
+  else
+    ccflags="${ccflags} -O3 -g0"
   fi
 
 else
@@ -310,6 +279,10 @@ fi
 
 # NOTE : if not using plugin at all -fPIC is not needed,
 #        but we have some in osc software.
-if [ `uname` = "Linux" ] ; then ccflags="${ccflags} -fPIC";fi
+if [ `uname` = "Linux" ] ; then
+  if [ ${build_visual} = "no" ] ; then
+    ccflags="${ccflags} -fPIC"
+  fi
+fi
 
 ccflags0="${ccflags}"
diff --git a/bush/use_cpp b/bush/use_cpp
--- a/bush/use_cpp
+++ b/bush/use_cpp
@@ -28,6 +28,12 @@ if [ ${build_gnu} = "yes" ] ; then
     elif [ "`echo ${osx_vers} | sed -e 's:10.12::g'`" != "${osx_vers}" ] ; then
       cpp_compiler=/opt/local/bin/g++-mp-5
       cpp_linker=/opt/local/bin/g++-mp-5
+    elif [ "`echo ${osx_vers} | sed -e 's:10.13::g'`" != "${osx_vers}" ] ; then
+      cpp_compiler=/opt/local/bin/g++-mp-5
+      cpp_linker=/opt/local/bin/g++-mp-5
+    elif [ "`echo ${osx_vers} | sed -e 's:10.14::g'`" != "${osx_vers}" ] ; then
+      cpp_compiler=/opt/local/bin/g++-mp-8
+      cpp_linker=/opt/local/bin/g++-mp-8
     else
       echo 'bush/use_cpp : g++ not found under /opt/local/bin.'
       exit
@@ -37,9 +43,10 @@ if [ ${build_gnu} = "yes" ] ; then
     cpp_linker=g++
   fi
 
-  if [ ${build_cxx11} = "yes" ] ; then
-    cppflags="${cppflags} -std=c++11"
-  fi
+ #if [ ${build_gnu11} = yes ] ; then cppflags="${cppflags} -std=gnu++11";fi
+ #if [ ${build_cxx11} = yes ] ; then cppflags="${cppflags} -std=c++11";fi
+ #if [ ${build_cxx14} = yes ] ; then cppflags="${cppflags} -std=c++14";fi
+ #if [ ${build_cxx17} = yes ] ; then cppflags="${cppflags} -std=c++17";fi
 
 elif [ ${build_intel} = "yes" ] ; then
   config_name=intel
@@ -61,46 +68,61 @@ elif [ ${build_clang} = "yes" ] ; then
       break
     fi
   done
-  
+
   if [ ${found} = no ] ; then
-    echo "${items} not found."
+    echo "bush/use_cpp : ${items} not found."
     exit
   fi
 
  #cppflags="${cppflags} -std=c++98"
  #cppflags="${cppflags} -ansi"
+
+ #if [ ${build_cxx11} = "yes" ] ; then
+ #  cppflags="${cppflags} -std=c++11"
+ # #cppflags="${cppflags} -stdlib=libc++"
+ #  if [ "`uname -n | grep iridium`" != "" ] ; then
+ #    cppflags="${cppflags} -I/usr/include/c++/v1"
+ #    cpp_linker_flags="${cpp_linker_flags} /usr/lib64/libc++.so"
+ #  fi
+ #fi
   
-  if [ ${build_cxx11} = "yes" ] ; then
-    cppflags="${cppflags} -std=c++11"
-   #cppflags="${cppflags} -stdlib=libc++"
-   
-    if [ "`uname -n | grep iridium`" != "" ] ; then
-      cppflags="${cppflags} -I/usr/include/c++/v1"
-      cpp_linker_flags="${cpp_linker_flags} /usr/lib64/libc++.so"
-    fi    
-  fi
+ #if [ ${build_cxx14} = yes ] ; then cppflags="${cppflags} -std=c++14";fi
+ #if [ ${build_cxx17} = yes ] ; then cppflags="${cppflags} -std=c++17";fi
+
+elif [ ${build_emcc} = "yes" ] ; then
+  config_name=emcc
+
+  ${bush_home}/check_app emcc 'bush/use_cpp : emcc not found.'
+  use_status=$?;
+  if [ ${use_status} != 0 ] ; then exit; fi
+
+  cpp_compiler=em++
+  cpp_linker=em++
+
+ #if [ ${build_cxx11} = yes ] ; then cppflags="${cppflags} -std=c++11";fi
+ #if [ ${build_cxx14} = yes ] ; then cppflags="${cppflags} -std=c++14";fi
+ #if [ ${build_cxx17} = yes ] ; then cppflags="${cppflags} -std=c++17";fi
 
 elif [ ${build_cling_clang} = "yes" ] ; then
   config_name=cling_clang
 
   . ${bush_home}/use_cling
-  
+
   if [ "${cling_home}" = "" ] ; then
     echo "bush/use_cpp : cling_home not defined."
     exit
   fi
-  
+
   if [ ${build_verbose} = yes ] ; then
     echo "bush/use_cpp : cling_home is ${cling_home}."
   fi
-  
+
   cpp_compiler=${cling_home}/bin/clang++
   cpp_linker=${cpp_compiler}
-  
-  if [ ${build_cxx11} = "yes" ] ; then
-    cppflags="${cppflags} -std=c++11"
-   #cppflags="${cppflags} -stdlib=libc++"
-  fi
+
+ #if [ ${build_cxx11} = yes ] ; then cppflags="${cppflags} -std=c++11";fi
+ #if [ ${build_cxx14} = yes ] ; then cppflags="${cppflags} -std=c++14";fi
+ #if [ ${build_cxx17} = yes ] ; then cppflags="${cppflags} -std=c++17";fi
 
 elif [ ${build_sdk_mac} = "yes" -o ${build_sdk_mac_gnu} = "yes" ] ; then
 
@@ -111,47 +133,19 @@ elif [ ${build_sdk_mac} = "yes" -o ${build_sdk_mac_gnu} = "yes" ] ; then
     config_name=sdk_mac
     cpp_compiler=clang++
     cpp_linker=clang++
-    if [ ${build_cxx11} = "yes" ] ; then
-      cppflags="${cppflags} -std=c++11 -stdlib=libc++"
-    fi
+   #if [ ${build_cxx11} = "yes" ] ; then cppflags="${cppflags} -std=c++11 -stdlib=libc++";fi
+   #if [ ${build_cxx14} = "yes" ] ; then cppflags="${cppflags} -std=c++14 -stdlib=libc++";fi
+   #if [ ${build_cxx17} = "yes" ] ; then cppflags="${cppflags} -std=c++17 -stdlib=libc++";fi
+
   else
     config_name=sdk_mac_gnu
     cpp_compiler=g++
     cpp_linker=g++
-    if [ ${build_cxx11} = "yes" ] ; then
-      cppflags="${cppflags} -std=c++11"
-    fi
+   #if [ ${build_cxx11} = yes ] ; then cppflags="${cppflags} -std=c++11";fi
+   #if [ ${build_cxx14} = yes ] ; then cppflags="${cppflags} -std=c++14";fi
+   #if [ ${build_cxx17} = yes ] ; then cppflags="${cppflags} -std=c++17";fi
     #Darwin : NOTE : we need a g++ knowing also objective-c++. /opt/local/bin/g++-mp-4.8 does not work.
   fi
- 
-  # 10.5  : Leopard
-  # 10.6  : Snow Leopard
-  # 10.7  : Lion
-  # 10.8  : Mountain Lion
-  # 10.9  : Mavericks
-  # 10.10 : Yosemite
-  # 10.11 : ElCapitan
-  # 10.12 : Sierra
-
-  # see also use_cc :
-  #sdk_dirs="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs /Developer/SDKs"
-  #sdk_verss="10.12 10.11 10.9 10.8 10.6 10.5"
-  #found=no
-  #for sdk_dir in ${sdk_dirs} ; do
-  #  for sdk_vers in ${sdk_verss} ; do
-  #    if [ ${found} = no ] ; then
-  #      macosx_sdk="${sdk_dir}/MacOSX${sdk_vers}.sdk"
-  #      macosx_vers=${sdk_vers}
-  #      if [ -d "${macosx_sdk}" ] ; then found=yes;fi
-  #    fi
-  #  done
-  #done
-  #if [ ${found} = no ] ; then
-  #  echo "bush/use_cpp : MacOSX sdk not found."
-  #  exit
-  #fi
-  #echo "${macosx_sdk}"
-  #echo "${macosx_vers}"
 
   osx_vers="`sw_vers -productVersion`"
   if [ "`echo ${osx_vers} | sed -e 's:10.6::g'`" != "${osx_vers}" ] ; then # old screenwall macs.
@@ -164,15 +158,15 @@ elif [ ${build_sdk_mac} = "yes" -o ${build_sdk_mac_gnu} = "yes" ] ; then
     macosx_sdk="/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"
   fi
 
-  if [ ${build_cxx11} = "yes" ] ; then
-    #macosx_target=10.7
-    # Xcode-8 : to avoid warning :
-    #  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
-    macosx_target=10.9
-    # Xcode-8 : end.
-  else 
+ #if [ ${build_cxx11} = "yes" -o ${build_cxx14} = "yes" ] ; then
+ #  #macosx_target=10.7
+ #  # Xcode-8 : to avoid warning :
+ #  #  clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of OS X 10.9
+ #  macosx_target=10.9
+ #  # Xcode-8 : end.
+ #else
     if [ "`echo ${osx_vers} | sed -e 's:10.6::g'`" != "${osx_vers}" ] ; then # old screenwall macs.
-     #macosx_target=10.6  
+     #macosx_target=10.6
       macosx_target=10.5
     else
       # Xcode-8 : to avoid warning :
@@ -181,12 +175,12 @@ elif [ ${build_sdk_mac} = "yes" -o ${build_sdk_mac_gnu} = "yes" ] ; then
       cppflags="${cppflags} -stdlib=libc++"
       # Xcode-8 : end.
     fi
-  fi
+ #fi
 
   if [ "${build_macosx_target}" != "" ] ; then
     macosx_target=${build_macosx_target}  # used in MEMPHYS/mgr/build_app_vis.
   fi
-  
+
   cppflags="${cppflags} -isysroot ${macosx_sdk}"
   cppflags="${cppflags} -mmacosx-version-min=${macosx_target}"
 
@@ -213,39 +207,22 @@ elif [ ${build_sdk_ios} = "yes" -o ${build_sdk_ios_gnu} = "yes" ] ; then
     cpp_compiler=clang++
     cpp_linker=clang++
     # for ioda, to avoid the "out of range problem" :
-    cppflags="${cppflags} -mno-thumb" 
-    if [ ${build_cxx11} = "yes" ] ; then
-      cppflags="${cppflags} -std=c++11 -stdlib=libc++"
-    fi
+    cppflags="${cppflags} -mno-thumb"
+    #if [ ${build_cxx11} = "yes" ] ; then
+    #  cppflags="${cppflags} -std=c++11 -stdlib=libc++"
+    #elif [ ${build_cxx14} = "yes" ] ; then
+    #  cppflags="${cppflags} -std=c++14 -stdlib=libc++"
+    #elif [ ${build_cxx17} = "yes" ] ; then
+    #  cppflags="${cppflags} -std=c++17 -stdlib=libc++"
+    #fi
   else
     config_name=sdk_ios_gnu
     cpp_compiler=/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin/llvm-g++-4.2
     cpp_linker=${cpp_compiler}
-    if [ ${build_cxx11} = "yes" ] ; then
-      cppflags="${cppflags} -std=c++11"
-    fi
+    #if [ ${build_cxx11} = yes ] ; then cppflags="${cppflags} -std=c++11";fi
+    #if [ ${build_cxx14} = yes ] ; then cppflags="${cppflags} -std=c++14";fi
+    #if [ ${build_cxx17} = yes ] ; then cppflags="${cppflags} -std=c++17";fi
   fi
-
-  # see also use_cc :
-  #sdk_dirs="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs /Developer/SDKs"
-  #sdk_verss="10.0 9.3 9.0 8.1 7.1 5.0"
-  #found=no
-  #for sdk_dir in ${sdk_dirs} ; do
-  #  for sdk_vers in ${sdk_verss} ; do
-  #    if [ ${found} = no ] ; then
-  #      ios_sdk="${sdk_dir}/iPhoneOS${sdk_vers}.sdk"
-  #      ios_vers=${sdk_vers}
-  #      if [ -d "${ios_sdk}" ] ; then found=yes;fi
-  #    fi
-  #  done
-  #done
-  #if [ ${found} = no ] ; then
-  #  echo "bush/use_cpp : iOS sdk not found."
-  #  exit
-  #fi
-  #echo "${ios_sdk}"
-  #echo "${ios_vers}"
-  #exit
 
   ios_sdk="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk"
   if [ ! -d "${ios_sdk}" ] ; then
@@ -275,7 +252,7 @@ elif [ ${build_sdk_ios} = "yes" -o ${build_sdk_ios_gnu} = "yes" ] ; then
   #   This was likely caused by different translation units being compiled with different visibility settings.
   cppflags="${cppflags} -fvisibility=hidden"
 
- #cppflags="${cppflags} -gdwarf-2 -mno-thumb" 
+ #cppflags="${cppflags} -gdwarf-2 -mno-thumb"
  #cppflags="${cppflags} -Os"
 
  #cppflags="${cppflags} -D__IPHONE_OS_VERSION_MIN_REQUIRED=30200"
@@ -326,7 +303,28 @@ elif [ ${build_visual} = "yes" ] ; then
     echo "bush/use_cpp : build_visual : bush_home not defined."
     exit
   fi
+
+  ${bush_home}/check_app cl.exe 'bush/use_cpp : cl.exe not found. You have to setup VisualC++.'
+  use_status=$?;
+  if [ ${use_status} != 0 ] ; then exit; fi
+
   cpp_compiler=${bush_home}/vc++
+
+ #if [ ${build_cxx11} = "yes" ] ; then cppflags="${cppflags} -std=c++11";fi
+ #if [ ${build_cxx14} = "yes" ] ; then
+ #  if [ "`uname -n`" = "PC-PANO" ] ; then
+ #    echo 'bush/use_cpp : c++14 not available on this machine.'
+ #    exit
+ #  fi
+ #  cppflags="${cppflags} -std=c++14"
+ #fi
+ #if [ ${build_cxx17} = "yes" ] ; then
+ #  if [ "`uname -n`" = "PC-PANO" ] ; then
+ #    echo 'bush/use_cpp : c++14 not available on this machine.'
+ #    exit
+ #  fi
+ #  cppflags="${cppflags} -std=c++17"
+ #fi
 
   if [ "${build_set_x}" = "yes" ] ; then cppflags="${cppflags} -verbose"; fi
 
@@ -337,76 +335,20 @@ elif [ ${build_visual} = "yes" ] ; then
 elif [ ${build_sdk_android} = "yes" ] ; then
   config_name=sdk_android
 
-  sdk_home=/usr/local/Android/android-sdk_r16-macosx
-  
-  # WARNING : must be in sync with use_cc, plugin, use/Android.
+  . ${bush_home}/use_android
 
- #build_ndk_vers=r15b
- #build_ndk_vers=r7
-  build_ndk_vers=r10e
-  
-  if [ ${build_verbose} = yes ] ; then
-    echo "bush/use_cpp : ndk version is ${build_ndk_vers}."
-  fi
-  
-  ndk_home=/usr/local/Android/android-ndk-${build_ndk_vers}
+  cpp_compiler=${ndk_cpp_compiler}
 
-  if [ ${build_ndk_vers} = r7 ] ; then
-    ndk_bin=${ndk_home}/toolchains/arm-linux-androideabi-4.4.3/prebuilt/darwin-x86/bin
-    ndk_platform="${ndk_home}/platforms/android-9/arch-arm"
-  elif [ ${build_ndk_vers} = r10e ] ; then
-    ndk_bin=${ndk_home}/toolchains/arm-linux-androideabi-4.8/prebuilt/darwin-x86_64/bin
-    ndk_platform="${ndk_home}/platforms/android-9/arch-arm"
-  else
-    echo "bush/use_cpp : ndk version ${build_ndk_vers} not yet supported."
-    exit
-  fi    
+  #if [ ${build_cxx11} = yes ] ; then cppflags="${cppflags} -std=c++11";fi
+  #if [ ${build_cxx14} = yes ] ; then cppflags="${cppflags} -std=c++14";fi
+  #if [ ${build_cxx17} = yes ] ; then cppflags="${cppflags} -std=c++17";fi
 
-  cpp_compiler=${ndk_bin}/arm-linux-androideabi-g++
-  
-  if [ ${build_cxx11} = "yes" ] ; then
+  if [ ${build_ndk_vers} = r17 ] ; then
     cppflags="${cppflags} -std=c++11"
   fi
 
- #if [ ${build_cxx11} = "yes" ] ; then
- #  cppflags="${cppflags} -std=c++11"
- #fi
-    
-  # same options as use_cc/ccflags :
-  if [ ${build_ndk_vers} = r7 ] ; then
-    cppflags="${cppflags} -D__ARM_ARCH_5__ -D__ARM_ARCH_5T__"
-    cppflags="${cppflags} -D__ARM_ARCH_5E__ -D__ARM_ARCH_5TE__"
-  fi
-  
-  cppflags="${cppflags} -fpic"
-  cppflags="${cppflags} -ffunction-sections -funwind-tables -fstack-protector"
-  cppflags="${cppflags} -fomit-frame-pointer -fno-strict-aliasing"
-  cppflags="${cppflags} -finline-limit=64"
-  
-  cppflags="${cppflags} -mthumb"
-  cppflags="${cppflags} -Os"
-  cppflags="${cppflags} -march=armv5te -mtune=xscale -msoft-float"
-  
-  cppflags="${cppflags} -Wno-psabi -Wa,--noexecstack"
-  
-  cppflags="${cppflags} -I${ndk_platform}/usr/include"
-
+  cppflags="${cppflags} ${ndk_cppflags}"
   cppflags="${cppflags} -DANDROID"
-
-  if [ ${build_ndk_vers} = r10e ] ; then
-    cppflags="${cppflags} -no-canonical-prefixes -Wformat -Werror=format-security"
-  fi
-  
-  # c++ flags :
-  #cppflags="${cppflags} -fno-exceptions -fno-rtti"
-  if [ ${build_ndk_vers} = r7 ] ; then
-    cppflags="${cppflags} -I${ndk_home}/sources/cxx-stl/gnu-libstdc++/include"
-    cppflags="${cppflags} -I${ndk_home}/sources/cxx-stl/gnu-libstdc++/libs/armeabi/include"
-  elif [ ${build_ndk_vers} = r10e ] ; then
-    cppflags="${cppflags} -I${ndk_home}/sources/cxx-stl/gnu-libstdc++/4.8/include"
-    cppflags="${cppflags} -I${ndk_home}/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi/include"
-    cppflags="${cppflags} -I${ndk_home}/sources/cxx-stl/gnu-libstdc++/4.8/include/backward"
-  fi
 
   cpp_linker=${cpp_compiler}
 
@@ -417,7 +359,11 @@ fi
 
 # NOTE : if not using plugin at all -fPIC is not needed,
 #        but we have some in osc software.
-if [ `uname` = "Linux" ] ; then cppflags="${cppflags} -fPIC";fi
+if [ `uname` = "Linux" ] ; then
+  if [ ${build_visual} = "no" ] ; then
+    cppflags="${cppflags} -fPIC"
+  fi
+fi
 
 if [ ${build_visual} = "yes" ] ; then
 
@@ -428,8 +374,18 @@ if [ ${build_visual} = "yes" ] ; then
     cppflags="${cppflags} -DNDEBUG"
   fi
 
-else
+elif [ ${build_emcc} = "yes" ] ; then
 
+  if [ ${build_debug} = "yes" ] ; then
+    cppflags="${cppflags} -g -g4"
+    cppflags="${cppflags} -s DEMANGLE_SUPPORT=1"
+    cppflags="${cppflags} -s ASSERTIONS=1"
+    cppflags="${cppflags} -Werror"
+  else
+    cppflags="${cppflags} -O3 -g0"
+  fi
+
+else
   if [ ${build_debug} = "yes" ] ; then
     cppflags="${cppflags} -g"
   else
@@ -467,13 +423,13 @@ elif [ ${build_sdk_android} = "yes" ] ; then
 
 else
 
-  if [ ${build_cxx11} = "yes" ] ; then
-    G4_cppflags="-W -Wall -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual"
-  else
-    G4_cppflags="-W -Wall -ansi -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual"
-    G4_cppflags="${G4_cppflags} -Wshadow"
-  fi
-  
+  G4_cppflags="-W -Wall -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual"
+  G4_cppflags="${G4_cppflags} -Wshadow"
+  #if [ ${build_cxx11} = "yes" -o ${build_gnu11} = "yes" -o ${build_cxx14} = "yes" ] ; then
+  #else
+  #  G4_cppflags="-W -Wall -ansi -pedantic -Wno-non-virtual-dtor -Wno-long-long -Wwrite-strings -Wpointer-arith -Woverloaded-virtual"
+  #fi
+
 fi
 
 if [ ${build_g4flags} = "yes" ] ; then
